/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SASCampaignNavigator;

import org.junit.Test;
import static org.junit.Assert.*;

public class MainTest {
    /*@Test public void testAppHasLogger() {
        Main classUnderTest = new Main();
        assertNotNull("Main should have a logger", classUnderTest.logger);
    }*/
}
